/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.team696.TCA9548ADriver;

import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;

public class TCA9548A {
    private byte selectedChannel=(byte)255;
    private Port port;
    private I2C muxi2c;

    public TCA9548A(Port port, int address){
        this.port = port;
        //this.muxAddress = address;
        this.muxi2c = new I2C(port, address);
        setChannel(0);
    }

    public Port getPort(){
        return port;
    }

    public void setChannel(byte channel){
        if(selectedChannel == channel){
            return;
        }
        byte[] data = {(byte)(1 << channel)};
        muxi2c.writeBulk(data, 1);
        selectedChannel = channel;
    }

    public void setChannel(int channel){
        setChannel((byte)channel);
    }

    public int getChannel(){
        return selectedChannel;
    }
    
}
